_target_ : models.generators.sean.SEANGenerator
num_filters_last_layer: 64
num_up_layers: 7
height: ${dataset.height}
width: ${dataset.width}
num_labels: ${dataset.num_labels}
style_dim: ${model.encoder.latent_dim}
kernel_size: 3
num_output_channels: ${dataset.num_channels}
apply_spectral_norm: True
use_vae: False