disc_optim:
  _target_: torch.optim.AdamW
  lr: ${model.optim.disc_lr}
  betas: ${model.optim.betas}
  weight_decay: ${model.optim.weight_decay}
gen_optim:
  _target_: torch.optim.AdamW
  lr: ${model.optim.gen_lr}
  betas: ${model.optim.betas}
  weight_decay: ${model.optim.weight_decay}
SAM: False
betas : [0.9, 0.999]
weight_decay: 0.01
disc_lr: 4e-4
gen_lr: 1e-4