_target_: albumentations.Compose
transforms:
  - _target_: albumentations.SmallestMaxSize 
    p: 1
    max_size:  ${dataset.height}
  - _target_: albumentations.CenterCrop
    p: 1
    height:  ${dataset.height}
    width:  ${dataset.width}
  - _target_: albumentations.HorizontalFlip
    p: 0.5    
  - _target_: albumentations.Normalize
    mean: 0.5
    std: 0.5
  - _target_: albumentations.pytorch.ToTensorV2