_target_: models.discriminators.patchgan.MultiScalePatchGanDiscriminator
num_discriminator: 2
image_num_channels: ${dataset.num_channels}
segmap_num_channels: ${dataset.num_labels}
num_features_fst_conv: 64
num_layers: 4
apply_spectral_norm: True
apply_grad_norm: False
keep_intermediate_results: True
use_equalized_lr: False
lr_mul: 1.0